# 開発専用のdocker-compose.yml です。 本番動作には production.yml を使います。
version: "3.1"
services:
  # 開発用のscaffoldなどのコマンド実行環境
  develop:
    build: .
    volumes:
      - .:/app
    working_dir: /app

  # Lumenバックエンド
  backend:
    build: backend
    command: "php -S 0.0.0.0:8081 -t public"
    ports:
      - "8081:8081"
    depends_on:
      - mariadb
    volumes:
      - ./backend:/app
      - ./backend/config/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
    env_file:
      - ./backend/.env.dev

  apisprout:
    image: danielgtaylor/apisprout
    volumes:
      - ./stubapi/api.yaml:/api.yaml
    command: /api.yaml
  stubapi:
    image: nginx:mainline-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./stubapi/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apisprout

  # create-react-app(&react-app-rewired)ベースのフロントエンド
  frontend:
    build: frontend
    command: "yarn start"
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/usr/src/app
      - frontend_cache:/usr/local/share/.cache
  
  mariadb:
    image: mariadb:10.3.5
    environment:
      MYSQL_DATABASE: muji_admin
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "23306:3306"
  deployer:
    restart: 'no'
    build: deployer
    command: 'echo "USE docker-compose run instead of docker-compose up"'
    volumes:
      - ./deployer:/deployer
  builder:
    restart: 'no'
    build:
      context: .
      dockerfile: ./builder/Dockerfile
    command: 'echo "USE docker-compose run instead of docker-compose up"'
    volumes:
      - .:/builder

volumes:
  frontend_cache:
