version: "3.1"
services:
  nginx: &nginx
    image: nginx:1.15
    restart: always
    volumes:
      - ./nginx/nginx-template.conf:/etc/nginx/conf.d/default.conf.template
      - ./frontend/build/static:/usr/share/nginx/html/static
      - ./nginx/robots.txt:/usr/share/nginx/html/robots.txt
    ports:
      - "80:80"
      - "443:443"
    command: /bin/sh -c "envsubst '$$HOST $$EN_SSL $$DIS_SSL $$DIS_BASIC' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    env_file:
      - .env
  nginx_local:
    <<: *nginx
    ports:
      - "8000:80"
  # APIサーバー
  backend:
    build: backend
    command: "php -S 0.0.0.0:8080 -t public"
    depends_on:
      - mariadb
    volumes:
      - ./backend:/app
      - ./backend/config/php-ini-overrides.ini:/etc/php/7.2/cli/conf.d/99-overrides.ini
    env_file:
      - ./backend/.env.dev
    ports:
      - 8080:8080

  # express.js による動作
  frontend:
    build: frontend
    command: "yarn serve"
    volumes:
      - ./frontend:/usr/src/app
    env_file:
      - ./.env
    ports:
      - 3000:3000

  # DB, APIサーバー向け
  mariadb:
    image: mariadb:10.3.5
    environment:
      MYSQL_DATABASE: muji_admin
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "23306:3306"
